// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = (function(_super) {
    __extends(App, _super);

    function App() {
      return App.__super__.constructor.apply(this, arguments);
    }

    App.prototype.initialize = function() {
      var deck, player;
      this.set('deck', deck = new Deck());
      this.set('playerHand', deck.dealPlayer());
      this.set('dealerHand', deck.dealDealer());
      player = this.get('playerHand');
      return player.on('bust', (function(_this) {
        return function() {
          console.log('received bust');
          return _this.disableHit();
        };
      })(this), this);
    };

    App.prototype.disableHit = function() {
      return this.disable('hit');
    };

    App.prototype.disable = function(button) {
      button || (button = 'all');
      return this.trigger('disable', button);
    };

    return App;

  })(Backbone.Model);

}).call(this);

//# sourceMappingURL=App.map
