// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Hand = (function(_super) {
    __extends(Hand, _super);

    function Hand() {
      return Hand.__super__.constructor.apply(this, arguments);
    }

    Hand.prototype.model = Card;

    Hand.prototype.initialize = function(array, deck, isDealer) {
      this.deck = deck;
      this.isDealer = isDealer;
    };

    Hand.prototype.canHit = function(status) {
      return this.set('canHit', status);
    };

    Hand.prototype.hit = function() {
      this.add(this.deck.pop()).last();
      return this.sendScore(this.scores(true));
    };

    Hand.prototype.stand = function() {
      return this.trigger('stand');
    };

    Hand.prototype.scores = function(app) {
      var hasAce, score;
      hasAce = this.reduce(function(memo, card) {
        return memo || card.get('value') === 1;
      }, false);
      score = this.reduce(function(score, card) {
        app || (app = card.get('revealed'));
        return score + (app ? card.get('value') : 0);
      }, 0);
      if (hasAce && score + 10 <= 21) {
        return [score + 10, score];
      } else {
        return [score];
      }
    };

    Hand.prototype.sendScore = function(score) {
      return this.trigger('score', score, this.length, JSON.stringify(this));
    };

    Hand.prototype.scoreRequest = function() {
      var score;
      return score = this.scores(true);
    };

    return Hand;

  })(Backbone.Collection);

}).call(this);

//# sourceMappingURL=Hand.map
